from __future__ import annotations

from typing import Protocol


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, password_hash: str | None) -> bool: ...


class TokenService(Protocol):
    def create_access_token(self, subject: str) -> str: ...
    def decode_access_token(self, token: str) -> dict: ...
